# starship configs

format = """
${custom.hostname_default}\
${custom.hostname_prod}\
$hostname\
$directory\
$git_branch\
$git_status\
$git_commit\
$git_state\
$shlvl\
$all\
$time\
$cmd_duration\
$battery\
$status\
$line_break\
$username\
(\
  \\(\
    ${env_var.KUBECTL_ENV}\
  \\)\
)\
$character"""

add_newline = false
palette = 'mypalette'

[battery]
charging_symbol = '🔌'
discharging_symbol = '🪫'

[custom.hostname_default]
command = 'uname -n | cut -d. -f1'
when = 'test -n "$SSH_CONNECTION" && test "$DOTFILES_ENV" != "PROD"'
style = 'green'
format = '@[$symbol$output]($style) '

[custom.hostname_prod]
command = 'uname -n | cut -d. -f1'
when = 'test -n "$SSH_CONNECTION" && test "$DOTFILES_ENV" == "PROD"'
style = 'red'
format = '@[$symbol$output]($style) '

[character]
success_symbol = '[>]()'
error_symbol = '[><](red)'

[cmd_duration]
format = '⌛[$duration]($style) '
style = 'bold slate-blue'

[directory]
truncation_length = 0
truncation_symbol = '…/'
truncate_to_repo = false
style = ''

[env_var.KUBECTL_ENV]
format = '[$env_value]($style)'
style = 'red'

[gcloud]
disabled = true
format = '[$symbol$active]($style) '
symbol = '☁️'

[gcloud.region_aliases]
asia-northeast1 = 'tokyo'
asia-northeast2 = 'osaka'

[git_branch]
format = '[$symbol$branch]($style)'
symbol = ''
#symbol = '🌱'
style = 'slate-blue'

[git_commit]
commit_hash_length = 7
format = '[#$hash(:$tag)]($style) '
style = 'green'
tag_disabled = false
tag_symbol = ''

[git_state]
format = '[*$state(\($progress_current/$progress_total\))*]($style) '
cherry_pick = '[🍒PICKING](bold pink)'
style = 'bold'

[git_status]
format = """
[\
  [$conflicted](yellow)\
  [$deleted](red)\
  [$renamed](lime)\
  [$modified](pink)\
  [$typechanged](purple)\
  [$staged](green)\
  [$untracked](bright-black)\
  [( $ahead_behind$stashed)](cyan)\
]($style) \
"""
style = ''
conflicted = '!'
deleted = '-'
renamed = '^'
modified = "*"
typechanged = ""
staged = "+"
untracked = "?"
stashed = "≡"

[hostname]
disabled = true
ssh_symbol = '🌐'
ssh_only = true
format = '[$ssh_symbol$hostname]($style) '
style = "green"

[palettes.mypalette]
blue = '#79bff9'
cyan = '#cbf9dc'
green = '#04dbb5'
lime = '#afff5f'
pink = '#d787af'
purple = '#8e80e8'
red = '#eb5b4e'
slate-blue = '#5f5fff'
yellow = '#f9eb4f'

[shlvl]
disabled = false
threshold = 3
format = '[\[$symbol$shlvl\]]($style) '
symbol = ''
style = ''

[status]
disabled = false
format = '[$symbol$status(:$common_meaning$signal_name$maybe_int)]($style) '
style = 'bold red'
symbol = '🔥'
pipestatus = true
map_symbol = true

[time]
disabled = false
format = '[$time]($style) '
style = 'bright-black'
time_format = '%Y-%m-%dT%H:%M:%S'
utc_time_offset = '+9'

[username]
format = '[$user]()'
