add_newline = true
format = """
$all$shlvl$time$cmd_duration$status$line_break\
$username$character"""

[character]
success_symbol = '[>]()'
error_symbol = '[!](167)'

[cmd_duration]
format = '⌛[$duration]($style) '
style = 'bold 63'

[directory]
truncation_length = 8
truncation_symbol = '…/'
truncate_to_repo = false
style = ''

[gcloud]
disabled = true
format = '[$symbol$active]($style) '
symbol = '☁️'

[gcloud.region_aliases]
asia-northeast1 = 'tokyo'
asia-northeast2 = 'osaka'

[git_branch]
symbol = '🌱'
format = '[$symbol$branch]($style) '
style = 'bold 63'

[git_commit]
commit_hash_length = 4
tag_symbol = '🔖'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold 167)'

[git_status]
style = 'bold 105'

[hostname]
format = '[$ssh_symbol$hostname]($style) '

[shlvl]
disabled = false
threshold = 3
format = '[\[$symbol$shlvl\]]($style) '
symbol = ''
style = ''

[status]
disabled = false
format = '[$symbol$status(:$common_meaning$signal_name$maybe_int)]($style) '
style = 'bold 167'
symbol = '🔥'
pipestatus = true
map_symbol = true

[time]
disabled = false
format = '[$time]($style) '
style = '43'
time_format = '%H:%M'
utc_time_offset = '+9'

[username]
format = '[$user]()'
