# starship configs

format = """
($username(@$hostname):)\
$directory\
$git_branch\
$git_status\
$git_commit\
$git_state\
$time\
(\
  (${env_var.KUBECTL_ENV} )\
)\
$battery\
$shlvl\
$cmd_duration\
$status\
$line_break\
$character\
"""

add_newline = false
palette = 'mypalette'

[battery]
charging_symbol = '🔌'
discharging_symbol = '🪫'

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

[cmd_duration]
format = '⌛[$duration]($style) '
style = 'purple'

[directory]
truncation_length = 0
truncation_symbol = '…/'
truncate_to_repo = false
style = 'purple'

[env_var.KUBECTL_ENV]
format = '[$env_value]($style)'
style = 'pink'

[gcloud]
disabled = true
format = '[$symbol$active]($style) '
symbol = '☁️'

[gcloud.region_aliases]
asia-northeast1 = 'tokyo'
asia-northeast2 = 'osaka'

[git_branch]
format = '[$symbol$branch]($style)'
symbol = ''
style = 'gray'

[git_commit]
commit_hash_length = 7
format = '[#$hash(:$tag)]($style) '
style = 'purple'
tag_disabled = false
tag_symbol = ''

[git_state]
format = '[*$state(\($progress_current/$progress_total\))*]($style) '
cherry_pick = '[🍒PICKING](bold pink)'
style = 'bold'

[git_status]
format = """
[\
  [$conflicted](yellow)\
  [$deleted](red)\
  [$renamed](sky)\
  [$modified](pink)\
  [$typechanged](gray)\
  [$staged](green)\
  [$untracked](bright-black)\
  [$ahead_behind](mint)\
  [$stashed](blue)\
]($style) \
"""
style = ''
conflicted = '!'
deleted = '-'
renamed = '~'
modified = '*'
typechanged = ''
staged = '+'
untracked = '?'
stashed = '='

[hostname]
disabled = false
ssh_only = true
format = '[$hostname]($style)'
style = 'purple'

[line_break]
disabled = false

[palettes.mypalette]
blue = '#417cff'
mint = '#c9f9dc'
green = '#0becca'
pink = '#ec94ad'
sky = '#7dbbfa'
purple = '#948cf3'
red = '#ea5950'
yellow = '#fcdc00'
gray = '#5e6164'

[shlvl]
disabled = false
threshold = 3
format = '[\[$symbol$shlvl\]]($style) '
symbol = ''
style = 'purple'

[status]
disabled = false
format = '[$symbol$status(:$common_meaning$signal_name$maybe_int)]($style) '
style = 'bold red'
symbol = '🔥'
pipestatus = true
map_symbol = true

[time]
disabled = false
format = '[$time]($style) '
style = 'gray'
time_format = '%Y-%m-%dT%H:%M:%S'
utc_time_offset = '+9'

[username]
format = '[$user]($style)'
show_always = false
style_user = 'purple'
