vim.loader.enable()
require("config.global")
require("config.options")
require("config.keymaps")
require("config.autocmd")
require("config.lazy")
require("config.colorscheme")
require("cursorinfo").setup()
