# Supported Version
# - tmux 3.4

# ------
# prefix
# ------

unbind C-b #default
set -g prefix C-j
bind C-j send-prefix

# ---------
# variables
# ---------

# colors
TMUX_COLOR_BLACK='#050a15'
TMUX_COLOR_WHITE='#eff7fe'
TMUX_COLOR_NAVY='#404c8b'
TMUX_COLOR_YELLOW='#fcdc00'
TMUX_COLOR_NEON_GREEN='#c7f761'
TMUX_COLOR_BLUE_PURPLE='#5f5fff'
TMUX_COLOR_PINK='#ec94ad'

# ---------------
# general settings
# ---------------

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-ghostty:Tc"
set -g history-limit 50000
set -g mouse on
set -g escape-time 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g display-time 2000
set -g display-panes-time 2000
set -g mode-keys vi
if-shell 'test -n "$TMUX_SHELL"' 'set -g default-shell "${TMUX_SHELL}"' 'set -g default-shell "${SHELL}"'

# -------------------------
# custom keyboard shortcuts
# -------------------------

unbind C-o #rotate-window
bind C-o select-pane -t :.+
bind C-p previous-window
bind C-n next-window
bind r source-file ~/.config/tmux/tmux.conf \; display '.tmux.conf reloaded'

# popup
bind C-a display-popup -xC -yC -w50% -h70% -E /usr/bin/env bash -c '\
  if [ "$(tmux display-message -p "#{session_name}")" == "popup" ]; then \
    tmux detach-client; \
  else \
    tmux attach -t popup || tmux new-session -s popup; \
  fi'
bind C-e display-popup -xC -yC -w90% -h90% -E /usr/bin/env bash -c '\
  if [ "$(tmux display-message -p "#{session_name}")" == "popup" ]; then \
    tmux detach-client; \
  else \
    tmux attach -t popup || tmux new-session -s popup; \
  fi'

# -----------
# appearances
# -----------

# status line
set -g status-interval 1
set -g status-position bottom
set -g status-justify centre
set -g status-style fg=terminal,bg=terminal
set -g status-left "#[fg=${TMUX_COLOR_WHITE},bg=${TMUX_COLOR_BLUE_PURPLE}]  SESSION:#S  #[default]"
set -g status-left-length 32
set -g status-right ' #{prefix_highlight} %Y/%m/%d(%a) %H:%M:%S '
set -g status-right-length 80
set -g window-status-separator ''
set -g window-status-format ' #I '
set -g window-status-current-format "#[fg=green,bold]*#[default]#I "

# message
set -g message-style fg="$TMUX_COLOR_WHITE",bg="$TMUX_COLOR_BLUE_PURPLE",fill="$TMUX_COLOR_BLUE_PURPLE"

# mode
set -g mode-style fg="$TMUX_COLOR_WHITE",bg="$TMUX_COLOR_BLUE_PURPLE"

# pane border
set -g pane-border-status off
set -g pane-border-lines single
set -g pane-border-style fg=default,bg=default
set -g pane-active-border-style fg="$TMUX_COLOR_PINK",bg=default
set -g pane-border-format ''
#set -g pane-border-format '#{?pane_active, [ #[fg=green#,bold]>#[default] #P ]  , [ #P ] }'

# clock
set -g clock-mode-style 24
set -g clock-mode-colour "$TMUX_COLOR_NEON_GREEN"

# -------
# plugins
# -------

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @prefix_highlight_fg 'black'
set -g @prefix_highlight_bg "$TMUX_COLOR_YELLOW"
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_copy_mode_attr "fg=${TMUX_COLOR_BLACK},bg=${TMUX_COLOR_NEON_GREEN}"
set -g @prefix_highlight_show_sync_mode 'on'
set -g @prefix_highlight_sync_mode_attr "fg=${TMUX_COLOR_BLACK},bg=${TMUX_COLOR_CYAN}"

if-shell 'test -d ~/.tmux/plugins/tpm' 'run "~/.tmux/plugins/tpm/tpm"'
